version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sharering-admin-panel
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/build_start.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
